name: Formatting Java Code with Google Java Format

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      # Install Google Java Format
      - name: Install Google Java Format
        run: |
          curl -Lo google-java-format.jar https://github.com/google/google-java-format/releases/download/v1.25.2/google-java-format-1.25.2-all-deps.jar

      # Format Java files
      - name: Format Java files with Google Java Format
        run: |
          find . -name "*.java" -print0 | xargs -0 -n1 java -jar google-java-format.jar --replace

      # Commit and push changes if any formatting was applied
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if ! git diff --quiet; then
            git add .
            git commit -m "chore: Auto-format Java code with Google Java Format [GitHub Action]"
            git push
          else
            echo "No changes to push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
