name: Formatting Java Code with Eclipse JDT

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Eclipse JDT Formatter
      - name: Download Eclipse JDT Formatter
        run: |
          curl -Lo eclipse-formatter.jar https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.core/3.32.0/org.eclipse.jdt.core-3.32.0.jar

      # Format Java files
      - name: Format Java files
        run: |
          find . -name "*.java" -print0 | xargs -0 -n1 java -jar eclipse-formatter.jar -config eclipse-java-google-style.xml -replace

      # Commit and push changes if any formatting was applied
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if ! git diff --quiet; then
            git add .
            git commit -m "chore: Auto-format Java code with Google Java Format [GitHub Action]"
            git push
          else
            echo "No changes to push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
